### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by repeatingwish** [arnold-yui-dib/Simple-Python-Discord-Bot#5]
C:\Users\ytarl\Downloads\Simple-Python-Discord-Bot-master>bot.py
Traceback (most recent call last):
  File "C:\Users\ytarl\Downloads\Simple-Python-Discord-Bot-master\bot.py", line 11, in <module>
    @client.command(pass_context=True)
  File "C:\Users\ytarl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.client.Client'>' object has no attribute 'command'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0384FBB0>

**Comment by arnold-yui-dib** [comment]
![image](https://user-images.githubusercontent.com/35906476/35542814-eb670ad4-0516-11e8-8baa-f9fb519ace59.png)
I think all you might have to do is change on_ready(ctx) to on_ready() if it works tell me

**Comment by arnold-yui-dib** [comment]
Correction: Do on_ready():
